DROP TABLE IF EXISTS makes;


CREATE TABLE makes(
id BIGINT PRIMARY KEY,
make VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX makes_name_un_id ON makes (make);


DROP TABLE IF EXISTS cars;

CREATE TABLE cars (
id SERIAL PRIMARY KEY,
vin VARCHAR(20) UNIQUE NOT NULL,
year INTEGER NOT NULL,
make_id BIGINT NOT NULL REFERENCES makes (id),
asking_price INTEGER NOT NULL,
model VARCHAR(50) NOT NULL
);