DROP TABLE cars;
DROP TABLE makes;

CREATE TABLE makes(
id BIGSERIAL PRIMARY KEY,
make VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX makes_make_un_id ON makes (make);

CREATE TABLE cars (
id SERIAL PRIMARY KEY,
vin VARCHAR(20) UNIQUE NOT NULL,
year INTEGER NOT NULL,
make_id BIGSERIAL NOT NULL REFERENCES makes (id),
asking_price INTEGER NOT NULL,
model VARCHAR(50) NOT NULL
);